name: Run unit tests and apiCheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: Validate binary compatibility of API
        # Use --no-daemon to allow caching of Gradle caches without running into locks.
        run: ./gradlew --no-daemon apiCheck
      - name: Run all tests
        # Use --no-daemon to allow caching of Gradle caches without running into locks.
        run: ./gradlew --no-daemon allTests
